export const REGISTER_USER = "REGISTER_USER";
export const PREDICT_DIABETES_8 = "PREDICT_DIABETES_8";
export const PREDICT_DIABETES_4 = "PREDICT_DIABETES_4";
export const INFO_SNACKBAR = "INFO_SNACKBAR";
export const SUCCESS_SNACKBAR = "SUCCESS_SNACKBAR";
export const FAILURE_SNACKBAR = "FAILURE_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
